language: node_js
node_js:
  - node
branches:
  only:
    - master
before_install:
  - git config --global user.name "Travis CI"
  - git config --global user.email "deploy@travis-ci.org"
install:
  - yarn install
script:
  - yarn build
  - yarn cov
after_success:
  - cp -r dist docs
  - cd docs
  - echo "kokoro.js.org" > CNAME
  - git init
  - git checkout --orphan gh-pages
  - git add -A
  - git commit -m "travis auto build"
  - git push --force https://$REPO_TOKEN@github.com/cool2645/kokoro.git gh-pages:gh-pages
