export const PLAY_ORDER_LOOP = 'PLAY_ORDER_LOOP'
export const PLAY_ORDER_SINGLE = 'PLAY_ORDER_SINGLE'
export const PLAY_ORDER_SHUFFLE = 'PLAY_ORDER_SHUFFLE'
export const PLAY_ORDER = [
  PLAY_ORDER_LOOP,
  PLAY_ORDER_SHUFFLE,
  PLAY_ORDER_SINGLE
]
